### ISSUE TITLE
RSS Feed in Chinese seems not able to be added.

### ISSUE THREAD

**Issue by AboutRSS** [flytaly/feedmailu#8]
Hi. Thanks for your creation. However, keep failing in adding RSS Feed in Chinese, like https://sspai.com/feed.

**Comment by flytaly** [comment]
Can you try again? Maybe it was a temporal problem because server couldn't get access to the feed.
It worked for me now
![Screenshot 2020-09-14 at 16 54 16](https://user-images.githubusercontent.com/1577569/93094871-204d5180-f6ab-11ea-9fb9-0e33d693fb4e.png)

**Comment by AboutRSS** [comment]
Aha, it works now. Great. Will add it to my list later. Thanks.
